### ISSUE TITLE
Additional and fixed ride requirements for new ride types

### ISSUE THREAD

**Issue by SpartanFrederic104** [jacknull1991/OpenRCT2.RideRequirements#1]
The Classic Mini Roller Coaster (aka the RCT1 Steel Mini Roller Coaster) has the same ride requirements as the Junior Roller Coaster, with the exception being the number of drops required is now 2 instead of 1. The Hybrid and Single Rail Roller Coasters also require a 10 meter drop instead of 9 (can still be bypassed with an inversion). The Log Flume also requires a 4 meter drop height.

The Alpine Coaster has the following ride requirements:
Max speed: 18 km/h (11 mph)
Max. negative vertical Gs: 0.40 g
Ride length: 370 m (1,214 ft)

**Comment by jacknull1991** [comment]
Added Alpine Coaster. I do not have this one in game so I can't test it myself.
Added Classic Mini Roller Coaster.
Added Classic Wooden Roller Coaster.
These two classic coasters are new ride types, and Classic Mini RC and Mini RC are 2 ride types so I kept them both.
Updated stats requirements for Log Flume, Hybrid Coaster, and Single Rail Coaster.
